#!/system/bin/sh

LINKNAME=$1

/system/bin/setprop "net.$LINKNAME.dns1" ""
/system/bin/setprop "net.$LINKNAME.dns2" ""
/system/bin/setprop "net.$LINKNAME.local-ip" ""
/system/bin/setprop "net.$LINKNAME.remote-ip" ""
/system/bin/setprop "net.$LINKNAME.gw" ""
/system/bin/setprop "net.$LINKNAME.if" ""
