#!/system/bin/sh

# This is needed for tethering to work

LINKNAME=$1

/system/bin/setprop "net.$LINKNAME.dns1" "$DNS1"
/system/bin/setprop "net.$LINKNAME.dns2" "$DNS2"
/system/bin/setprop "net.$LINKNAME.local-ip" "$IPLOCAL"
/system/bin/setprop "net.$LINKNAME.remote-ip" "$IPREMOTE"
/system/bin/setprop "net.$LINKNAME.gw" "$IPREMOTE"
/system/bin/setprop "net.$LINKNAME.if" "$IFNAME"
